version: '3.0'
services:
  db:
    image: timescale/timescaledb:latest-pg12
    ports:
      - "5432:5432/tcp"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
#    entrypoint:
#      - "/bin/bash"
#    command:
#      - "/bin/bash"
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_USER: postgres
